"""Rutas y parámetros compartidos por RimayMaki."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATASETS_DIR = ROOT / "datasets"
MODELS_DIR = ROOT / "models"

CAMERA_INDEX = 0
MAX_HANDS = 1
SEQUENCE_LENGTH = 20
PREDICTION_HISTORY_SIZE = 5
VECTOR_SIZE = 63
MIN_SAMPLES_PER_CLASS = 20
CONFIDENCE_THRESHOLD = 0.80
RECOGNITION_FPS = 10
DEBUG_MODE = False
TOTAL_ROUNDS = 10
POINTS_PER_CORRECT = 100
STREAK_BONUS_PER_LEVEL = 10
